#include "cuda_functions.h"
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include <thrust/device_vector.h>
#include <thrust/sequence.h>
#include <thrust/execution_policy.h>
#include <thrust/sort.h>
#include <thrust/gather.h>
#include <stdio.h>
#include <glm/glm.hpp>
#include "Grid.cuh"